service: json-crud

frameworkVersion: "3"

custom:
  bucket: fake-api-aug
  force: undefined

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:GetObjectAcl
            - s3:PutObject
            - s3:PutObjectAcl
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  json-crud:
    handler: handler.jsonCrud
    environment:
      BUCKET: ${self:custom.bucket}
      FORCE_DELETE_FIELD: ${self:custom.force}
